# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SAS Games Cards
email: gkoeser@sasgames.net
description: > # this means to ignore newlines until "baseurl:"
  Custom card games for your event by Greg Koeser / Short Attention
  Span Games.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cards.sasgames.net" # the base hostname & protocol for your site
twitter_username: gkoeser
github_username:

# Build settings
markdown: kramdown
